services:
  - type: web
    name: YNAB Custom Reports
    runtime: static
    repo: https://github.com/grantwforsythe/ynab-custom-reports
    branch: main
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    staticPublishPath: dist/ynab-custom-reports/browser
    buildFilter:
      paths:
        - src/**/*.ts
      ignoredPaths:
        - src/**/*.spec.ts
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
      - key: HUSKY
        value: 0
