name: Release and deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node, npm, and dependencies
        uses: ./.github/actions/install-dependencies

      - name: Initialize Git User
        run: |
          git config --global user.email "grantwforsythe@gmail.com"
          git config --global user.name "Release Workflow"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release --ci

      - name: Deploy to Render
        env:
          DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL}}
        run: curl "$DEPLOY_HOOK_URL"
        shell: bash
